inc: no idea why jails are special...
We can dash out jails, use them for development or production
environments even.  Sure, they may not support some priviledged
operation, but keeping weird glue around that is probably not
in all the places it should be is weird.

diff --git a/src/etc/rc b/src/etc/rc
--- a/src/etc/rc
+++ b/src/etc/rc
@@ -107,22 +107,20 @@ else
 		/usr/bin/make -C /root/core mount
 	fi
 
-	if [ ! "$PLATFORM" = "jail" ]; then
-		# Check to see if a compact flash mountpoint exists
-		# If it fails to mount then run a fsck -y
-		if grep -q cf /etc/fstab; then
+	# Check to see if a compact flash mountpoint exists
+	# If it fails to mount then run a fsck -y
+	if grep -q cf /etc/fstab; then
+		/sbin/mount -w /cf 2>/dev/null
+		/sbin/mount -uw /cf 2>/dev/null
+		mount_rc=$?
+		attempts=0
+		while [ ${mount_rc} != 0 -a ${attempts} -lt 3 ]; do
+			/sbin/umount /cf
+			/sbin/fsck -y /cf
 			/sbin/mount -w /cf 2>/dev/null
-			/sbin/mount -uw /cf 2>/dev/null
 			mount_rc=$?
-			attempts=0
-			while [ ${mount_rc} != 0 -a ${attempts} -lt 3 ]; do
-				/sbin/umount /cf
-				/sbin/fsck -y /cf
-				/sbin/mount -w /cf 2>/dev/null
-				mount_rc=$?
-				attempts=$((attempts+1))
-			done
-		fi
+			attempts=$((attempts+1))
+		done
 	fi
 
 	USE_MFS_TMPVAR=`/usr/bin/grep -c use_mfs_tmpvar /cf/conf/config.xml`
@@ -166,10 +164,8 @@ if [ "$PLATFORM" = "pfSense" ] && [ ${USE_MFS_TMPVAR} -eq 0 ]; then
 	/sbin/mdmfs -S -M -s 4m md /var/run
 fi
 
-if [ ! "$PLATFORM" = "jail" ]; then
-	# Enable console output if its muted.
-	/sbin/conscontrol mute off >/dev/null
-fi
+# Enable console output if its muted.
+/sbin/conscontrol mute off >/dev/null
 
 if [ "$PLATFORM" = "cdrom" ] ; then
 	# do nothing for cdrom platform
@@ -182,8 +178,6 @@ elif [ "$PLATFORM" = "nanobsd" ] || [ ${USE_MFS_TMPVAR} -gt 0 ]; then
 	/bin/mkdir -p /root/var/db/pbi
 	/bin/rm -rf /var/db/pbi
 	/bin/ln -s /root/var/db/pbi/ /var/db/pbi
-elif [ "$PLATFORM" = "jail" ]; then
-	# do nothing for jail platform
 else
 	/sbin/swapon -a
 	/usr/local/etc/rc.savecore
@@ -309,11 +303,10 @@ done
 /bin/chmod 0600 /var/log/*.log
 
 echo -n "."
-if [ ! "$PLATFORM" = "jail" ]; then
-	DEVFS=`/sbin/mount | /usr/bin/grep devfs | /usr/bin/wc -l | /usr/bin/cut -d" " -f8`
-	if [ "$DEVFS" = "0" ]; then
-		mount_devfs devfs /dev
-	fi
+
+DEVFS=`/sbin/mount | /usr/bin/grep devfs | /usr/bin/wc -l | /usr/bin/cut -d" " -f8`
+if [ "$DEVFS" = "0" ]; then
+	mount_devfs devfs /dev
 fi
 
 # Create an initial utmp file
@@ -323,20 +316,18 @@ echo -n "."
 /sbin/ldconfig -elf /usr/lib /usr/local/lib /lib
 /etc/rc.d/ldconfig start 2>/dev/null
 
-if [ ! "$PLATFORM" = "jail" ]; then
-	# Launching kbdmux(4)
-	if [ -f "/dev/kbdmux0" ]; then
-		echo -n "."
-		/usr/sbin/kbdcontrol -k /dev/kbdmux0 < /dev/console
-		[ -c "/dev/atkbd0" ] && kbdcontrol -a atkbd0 < /dev/console
-		[ -c "/dev/ukbd0" ] && kbdcontrol -a ukbd0 < /dev/console
-	fi
+# Launching kbdmux(4)
+if [ -f "/dev/kbdmux0" ]; then
+	echo -n "."
+	/usr/sbin/kbdcontrol -k /dev/kbdmux0 < /dev/console
+	[ -c "/dev/atkbd0" ] && kbdcontrol -a atkbd0 < /dev/console
+	[ -c "/dev/ukbd0" ] && kbdcontrol -a ukbd0 < /dev/console
+fi
 
-	# Fire up unionfs if mount points exist.
-	if [ -f /dist/uniondirs ]; then
-		echo -n "."
-		/etc/rc.d/unionfs start
-	fi
+# Fire up unionfs if mount points exist.
+if [ -f /dist/uniondirs ]; then
+	echo -n "."
+	/etc/rc.d/unionfs start
 fi
 
 echo "done."
