sbin: merge ZFS support for opnsense-importer utility

diff --git a/src/sbin/opnsense-importer b/src/sbin/opnsense-importer
--- a/src/sbin/opnsense-importer
+++ b/src/sbin/opnsense-importer
@@ -52,8 +52,15 @@ bootstrap_and_exit()
 
 	# clean up after a finished import
 	if [ -d ${MNT} ]; then
-		umount ${MNT} 2> /dev/null
-		rm -rf ${MNT}
+		if [ -n "${PART}" ]; then
+			umount ${MNT} && rm -rf ${MNT}
+		elif [ -n "${POOL}" ]; then
+			zpool export ${POOL} && rm -rf ${MNT}
+		fi
+	fi
+
+	if [ -z "${ZFS}" ]; then
+		kldunload zfs
 	fi
 
 	# error code given or assumed ok (trap)
@@ -103,6 +110,16 @@ timeout_prompt()
 	return ${RETURN}
 }
 
+zfs_load()
+{
+	# we need to load ZFS to list pools
+	if kldstat -qm zfs; then
+		export ZFS="yes"
+	else
+		kldload zfs
+	fi
+}
+
 probe_for_part()
 {
 	DEV=${1}
@@ -115,6 +132,11 @@ probe_for_part()
 		# GPT layout found
 		export PART="/dev/${DEV}p3"
 		return 0
+	elif [ "${DEV}" = "zroot" ]; then
+		if zpool import | awk '{ print $1 " " $2 }' | grep -q "${DEV} ONLINE"; then
+			export POOL="${DEV}"
+			return 0
+		fi
 	fi
 
 	return 1
@@ -124,6 +146,8 @@ DEVS=
 PART=
 
 if [ -n "${1}" ]; then
+	zfs_load
+
 	if ! probe_for_part ${1}; then
 		echo "No previous configuration was found on this device."
 		bootstrap_and_exit 1
@@ -141,10 +165,12 @@ else
 		fi
 	fi
 
+	zfs_load
+
 	DEVS=$(camcontrol devlist; gmirror status -s; graid status -s)
 fi
 
-while [ -z "${PART}" ]; do
+while [ -z "${PART}" -a -z "${POOL}" ]; do
 	echo
 	echo "${DEVS}"
 	echo
@@ -161,18 +187,28 @@ while [ -z "${PART}" ]; do
 	fi
 done
 
-echo "Starting import for partition '${PART}'."
-echo
-
 mkdir -p ${MNT}
 
-echo -n "Running fsck..."
-fsck -t ufs -y ${PART} > /dev/null
-echo "done."
+if [ -n "${PART}" ]; then
+	echo "Starting import for partition '${PART}'."
+	echo
 
-if ! mount ${PART} ${MNT} 2> /dev/null; then
-	echo "The device could not be mounted."
-	bootstrap_and_exit 1
+	echo -n "Running fsck..."
+	fsck -t ufs -y ${PART} > /dev/null
+	echo "done."
+
+	if ! mount ${PART} ${MNT}; then
+		echo "The device could not be mounted."
+		bootstrap_and_exit 1
+	fi
+elif [ -n "${POOL}" ]; then
+	echo "Starting import for ZFS pool '${POOL}'."
+	echo
+
+	zpool import -f -R ${MNT} ${POOL}
+	if ! zfs mount ${POOL}/ROOT/default; then
+		echo "The device could not be mounted."
+	fi
 fi
 
 if [ -f "${MNT}/conf/config.xml" ]; then
