Revert "update to opnsense/core master"

diff --git a/src/sbin/opnsense-importer b/src/sbin/opnsense-importer
--- a/src/sbin/opnsense-importer
+++ b/src/sbin/opnsense-importer
@@ -59,7 +59,9 @@ bootstrap_and_exit()
 		fi
 	fi
 
-	zfs_unload
+	if [ -z "${ZFS}" ]; then
+		kldunload zfs
+	fi
 
 	# error code given or assumed ok (trap)
 	if [ -z "${RET}" ]; then
@@ -69,13 +71,12 @@ bootstrap_and_exit()
 	exit "${RET}"
 }
 
-while getopts bz OPT; do
+trap bootstrap_and_exit 2
+
+while getopts b OPT; do
 	case ${OPT} in
 	b)
 		DO_BOOT="-b"
-		;;
-	z)
-		DO_ZFS="-z"
 		;;
 	*)
 		echo "Usage: man opnsense-importer" >&2
@@ -85,8 +86,6 @@ while getopts bz OPT; do
 done
 
 shift $((${OPTIND} - 1))
-
-DO_DEV=${1}
 
 timeout_prompt()
 {
@@ -114,39 +113,14 @@ timeout_prompt()
 zfs_load()
 {
 	# we need to load ZFS to list pools
-	if ! kldstat -qm zfs; then
-		export UNLOAD_ZFS="yes"
+	if kldstat -qm zfs; then
+		export ZFS="yes"
+	else
 		kldload zfs
 	fi
-
-	export POOLS=$(zfs_probe)
-	if [ -n "${POOLS}" ]; then
-		# insert missing newline due to $()
-		export POOLS="${POOLS}
-"
-	fi
 }
 
-zfs_unload()
-{
-	if [ -n "${UNLOAD_ZFS}" ]; then
-		kldunload zfs
-	fi
-}
-
-zfs_probe()
-{
-	zpool import -aNf
-
-	zpool get -H cachefile | while read ZPOOL ZMORE; do
-		if [ "$(mount | grep -w / | grep -c ${ZPOOL})" = "0" ]; then
-			zpool export ${ZPOOL} >/dev/null 2>/dev/null
-			echo "zfs/${ZPOOL}"
-		fi
-	done
-}
-
-import_start()
+probe_for_part()
 {
 	local DEV=${1}
 
@@ -158,10 +132,11 @@ import_start()
 		# GPT UFS
 		export PART="/dev/${DEV}p3"
 		return 0
-	elif [ "$(echo ${POOLS} | grep -c ^${DEV}$)" != "0" ]; then
-		# ZFS POOL
-		export POOL="${DEV##zfs/}"
-		return 0
+	elif [ "${DEV}" = "zroot" ]; then
+		if zpool import | awk '{ print $1 " " $2 }' | grep -q "${DEV} ONLINE"; then
+			export POOL="${DEV}"
+			return 0
+		fi
 	elif [ -e "/dev/${DEV}s1" ]; then
 		# MBR MSDOS
 		export PART="/dev/${DEV}s1"
@@ -177,47 +152,37 @@ import_start()
 	return 1
 }
 
-
-DEV=
+DEV=${1}
 DEVS=
 PART=
-POOL=
-POOLS=
 
-if [ -n "${DO_ZFS}" ]; then
+if [ -n "${DEV}" ]; then
 	zfs_load
-	zfs_unload
-	echo -n "${POOLS}"
-	exit 0
-fi
 
-trap bootstrap_and_exit 2
-
-if [ -n "${DO_BOOT}" ]; then
-	touch ${INSTALL} 2> /dev/null
-	if [ -f ${INSTALL} -a -f /conf/config.xml ]; then
-		bootstrap_and_exit 0
-	fi
-
-	if ! timeout_prompt \
-	    'Press any key to start the configuration importer:' ${WAIT}; then
-		bootstrap_and_exit 0
-	fi
-fi
-
-zfs_load
-
-if [ -n "${DO_DEV}" ]; then
-	if ! import_start ${DO_DEV}; then
-		echo "No known partition layout was found for '${DO_DEV}'."
+	if ! probe_for_part ${DEV}; then
+		echo "No known partition layout was found for '${DEV}'."
 		bootstrap_and_exit 1
 	fi
+else
+	if [ -n "${DO_BOOT}" ]; then
+		touch ${INSTALL} 2> /dev/null
+		if [ -f ${INSTALL} -a -f /conf/config.xml ]; then
+			bootstrap_and_exit 0
+		fi
+
+		if ! timeout_prompt \
+		    'Press any key to start the configuration importer:' ${WAIT}; then
+			bootstrap_and_exit 0
+		fi
+	fi
+
+	zfs_load
+
+	DEVS=$(camcontrol devlist; gmirror status -s; graid status -s)
 fi
 
-DEVS=$(camcontrol devlist; gmirror status -s; graid status -s; echo -n "${POOLS}")
-
 while : ; do
-	if [ -z "${DO_DEV}" ]; then
+	if [ -z "${DEV}" ]; then
 		echo
 		echo "${DEVS}"
 		echo
@@ -229,11 +194,15 @@ while : ; do
 		elif [ "${DEV}" = "!" ]; then
 			# secret escape! (not so secret now, is it?)
 			csh
+			DEV=
 			continue
-		elif ! import_start ${DEV}; then
+		elif ! probe_for_part ${DEV}; then
 			echo "No known partition layout was found for '${DEV}'."
+			DEV=
 			continue
 		fi
+
+		DEV=
 	fi
 
 	mkdir -p ${MNT}
@@ -256,56 +225,52 @@ while : ; do
 			echo "The device could not be mounted."
 			PART=
 		fi
+
+		break
 	elif [ -n "${POOL}" ]; then
 		echo "Starting import for ZFS pool '${POOL}'."
 		echo
 
-		zpool import -fNR ${MNT} ${POOL}
-		if ! mount -t zfs ${POOL}/ROOT/default ${MNT}; then
-			echo "The pool could not be mounted."
+		zpool import -f -R ${MNT} ${POOL}
+		if ! zfs mount ${POOL}/ROOT/default; then
+			echo "The device could not be mounted."
 			POOL=
 		fi
-	fi
 
-	if [ -z "${PART}" -a -z "${POOL}" ]; then
-		if [ -n "${DO_DEV}" ]; then
-			bootstrap_and_exit 1
-		fi
-
-		continue
-	fi
-
-	if [ -f "${MNT}/conf/config.xml" ]; then
-		rm -rf /conf/*
-
-		for FILE in captiveportal.sqlite config.xml dhcpleases.tgz dhcp6c_duid netflow.tgz rrd.tgz; do
-			if [ -f "${MNT}/conf/${FILE}" ]; then
-				echo -n "Restoring ${FILE}..."
-				cp "${MNT}/conf/${FILE}" /conf
-				echo "done."
-			fi
-		done
-
-		for DIR in backup sshd; do
-			if [ -d "${MNT}/conf/${DIR}" ]; then
-				echo -n "Restoring ${DIR}..."
-				cp -r "${MNT}/conf/${DIR}" /conf
-				echo "done."
-			else
-				mkdir -p "/conf/${DIR}"
-			fi
-		done
-
-		# hooray, we're done!
 		break
 	else
-		echo "No previous configuration was found."
+		echo "Something went wrong during partition selection."
+		bootstrap_and_exit 1
+	fi
 
-		if [ -n "${DO_DEV}" ]; then
-			bootstrap_and_exit 1
-		fi
+	if [ -n "${DEV}" ]; then
+		echo "Import from partition '${DEV}' failed."
+		bootstrap_and_exit 1
 	fi
 done
+
+if [ -f "${MNT}/conf/config.xml" ]; then
+	rm -rf /conf/*
+	for FILE in captiveportal.sqlite config.xml dhcpleases.tgz dhcp6c_duid netflow.tgz rrd.tgz; do
+		if [ -f "${MNT}/conf/${FILE}" ]; then
+			echo -n "Restoring ${FILE}..."
+			cp "${MNT}/conf/${FILE}" /conf
+			echo "done."
+		fi
+	done
+	for DIR in backup sshd; do
+		if [ -d "${MNT}/conf/${DIR}" ]; then
+			echo -n "Restoring ${DIR}..."
+			cp -r "${MNT}/conf/${DIR}" /conf
+			echo "done."
+		else
+			mkdir -p "/conf/${DIR}"
+		fi
+	done
+else
+	echo "No previous configuration was found on this device."
+	bootstrap_and_exit 1
+fi
 
 if [ -z "${DO_BOOT}" ]; then
 	echo "Please reboot."
