firmware: allow size or version read from other components

diff --git a/src/sbin/opnsense-version b/src/sbin/opnsense-version
--- a/src/sbin/opnsense-version
+++ b/src/sbin/opnsense-version
@@ -23,13 +23,50 @@
 # ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 # POSSIBILITY OF SUCH DAMAGE.
 
-VERSION="/usr/local/opnsense/version/opnsense"
+VERSIONDIR="/usr/local/opnsense/version"
 OPENSSL="/usr/local/bin/openssl"
 OUTPUT=
+
+DO_PKG="-p opnsense"
+DO_SIZE=
+
+while getopts p:s OPT; do
+	case ${OPT} in
+	p)
+		DO_PKG="-p ${OPTARG}"
+		;;
+	s)
+		DO_SIZE="-s"
+		;;
+	*)
+		echo "Usage: man opnsense-version" >&2
+		exit 1
+		;;
+	esac
+done
+
+shift $((${OPTIND} - 1))
+
+VERSION="${VERSIONDIR}/${DO_PKG#"-p "}"
+
+if [ -n "${DO_SIZE}" ]; then
+	if [ ! -f ${VERSION}.size ]; then
+		echo "Missing ${VERSION}.size" >&2
+		exit 1
+	fi
+
+	cat ${VERSION}.size
+	exit 0
+fi
 
 if [ ! -f ${VERSION} ]; then
 	echo "Missing ${VERSION}" >&2
 	exit 1
+fi
+
+if [ "${DO_PKG}" != "-p opnsense" ]; then
+	cat ${VERSION}
+	exit 0
 fi
 
 eval "$(grep -v '[{}]' ${VERSION} | sed 's/[^"]*"\([^"]*\)"[^"]*"\([^"]*\)".*/\1="\2"/')"
